import ProfileCard from "@/components/ProfileCard";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Profile Card Component</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon-32x32.png" />
      </Head>

      <main>
        <ProfileCard />
      </main>
    </>
  );
}
